#!/bin/bash
# -*- mode: sh -*-

#*BeginPNNLCopyright*********************************************************
#
# $HeadURL$
# $Id: 0cae9f95d9ed0841bbf77c91eef5f3d4c9a73f2e $
#
#***********************************************************EndPNNLCopyright*

# set -x

scriptPath0="${BASH_SOURCE[0]}" # works when script is sourced (unlike $0)
scriptPath=$(readlink -f "${scriptPath0}")
scriptCmd=${scriptPath##*/} # cf. $(basename ...)
scriptDir=${scriptPath%/*}  # cf. $(dirname ...)

#****************************************************************************

# https://misc.flogisoft.com/bash/tip_colors_and_formatting
ClrBeg=$'\e[1m\e[4m\e[31m' # '$' syntax quotes escapes
ClrEnd=$'\e[0m'

#-----------------------------------------------------------

# Canonical ${scriptDir} is ${DATALIFE_ROOT}/bin
DATALIFE_ROOT="${DATALIFE_ROOT:-${scriptDir}/../}"

#-----------------------------------------------------------

#datalife_lib="${DATALIFE_ROOT}/libexec/flow-analysis"
datalife_lib=${scriptDir}/../libexec/flow-analysis/

cmd=${datalife_lib}/bin/${scriptCmd}.py

#-----------------------------------------------------------------------------

is_debug=0

if [[ $1 =~ ^--debug ]] ; then
    is_debug=1
fi


#****************************************************************************

if (( $is_debug )) ; then
    cat <<EOF
${ClrBeg}Hello from: ${scriptPath}${ClrEnd}
  datalife_lib = '${datalife_lib}'
  cmd          = '${cmd}'
EOF
fi

export PYTHONPATH+="${datalife_lib}"

exec "${cmd}" "$@"
