#!/bin/bash
# -*- mode: sh -*-

#*BeginPNNLCopyright*********************************************************
#
# $HeadURL$
# $Id: 0cae9f95d9ed0841bbf77c91eef5f3d4c9a73f2e $
#
#***********************************************************EndPNNLCopyright*

# set -x

scriptPath0="${BASH_SOURCE[0]}" # works when script is sourced (unlike $0)
scriptPath=$(readlink -f "${scriptPath0}")
scriptCmd=${scriptPath##*/} # cf. $(basename ...)
scriptDir=${scriptPath%/*}  # cf. $(dirname ...)

#****************************************************************************

# https://misc.flogisoft.com/bash/tip_colors_and_formatting
ClrBeg=$'\e[1m\e[4m\e[31m' # '$' syntax quotes escapes
ClrEnd=$'\e[0m'

datalife_lib=${scriptDir}/src # TODO: update for official install

cmd=${datalife_lib}/${scriptCmd}

#-----------------------------------------------------------------------------

if [[ $1 =~ ^--debug ]] ; then
    cat <<EOF
${ClrBeg}Hello from: ${scriptPath}${ClrEnd}
  datalife_lib=${datalife_lib}
  cmd=${cmd}
EOF
    #exit
fi

#-----------------------------------------------------------------------------

PYTHONPATH+=${datalife_lib} "${cmd}" "$@"
